import { Colors } from '@/constants/theme';

export type PillarKey =
  | 'Confidence'
  | 'Abundance'
  | 'Love'
  | 'Health'
  | 'Peace'
  | 'Focus';

export const AFFIRMATION_PILLARS: Record<
  PillarKey,
  { title: string; icon: string; color: string; messages: string[] }
> = {
  Confidence: {
    title: 'Self-Worth & Confidence',
    icon: 'flash',
    color: Colors.chakra.orange,
    messages: [
      'I trust myself and honor my worth every day.',
      'I speak up with clarity and confidence.',
      'I deserve respect and I receive it naturally.',
      'I stand tall in my power and authenticity.',
      'My voice matters and I use it wisely.',
      'I am proud of who I am becoming.',
      'I meet challenges with courage and calm.',
      'I release comparison and celebrate my path.',
      'My boundaries protect my peace and my growth.',
      'I learn from mistakes without shrinking myself.',
      'I show up fully, even when I feel unsure.',
      'I am enough exactly as I am right now.',
      'Confidence grows when I keep my promises to myself.',
      'I radiate quiet strength people can feel.',
      'I choose boldness over playing small.',
      'I forgive myself and move forward with dignity.',
    ],
  },
  Abundance: {
    title: 'Wealth & Abundance',
    icon: 'cash',
    color: Colors.chakra.green,
    messages: [
      'Money flows to me in expected and unexpected ways.',
      'I am a magnet for wealth, opportunities, and prosperity.',
      'Abundance is my natural state and I receive it freely.',
      'I deserve financial freedom and live it every day.',
      'My income increases steadily and joyfully.',
      'I release scarcity beliefs and embrace infinite supply.',
      'I manage money with clarity and intention.',
      'Opportunity finds me because I am ready for it.',
      'I invest in myself and my future with confidence.',
      'Gratitude opens doors that fear kept closed.',
      'I celebrate others’ wins without dimming my own.',
      'Resources stretch further when I trust and plan.',
      'I earn, save, and spend in alignment with my values.',
      'Abundance includes time, health, love, and ease.',
      'I welcome new streams of income with gratitude.',
      'I am worthy of stability, comfort, and generosity.',
    ],
  },
  Love: {
    title: 'Love & Relationships',
    icon: 'heart',
    color: Colors.chakra.red,
    messages: [
      'I am deeply loved in healthy, reciprocal relationships.',
      'I attract people who respect and value me.',
      'I give and receive love with ease.',
      'My relationships are safe, kind, and supportive.',
      'I communicate honestly and lovingly.',
      'Love expands in my life every day.',
      'I choose connection without losing myself.',
      'I repair ruptures with patience and care.',
      'My heart softens without abandoning my standards.',
      'I trust love that is steady, not performative.',
      'I am a good friend and I receive friendship in return.',
      'Intimacy grows when I show up authentically.',
      'I release relationships that drain my spirit.',
      'Kindness begins with how I treat myself.',
      'I celebrate love in many forms around me.',
      'I am worthy of devotion, tenderness, and truth.',
    ],
  },
  Health: {
    title: 'Health & Vitality',
    icon: 'fitness',
    color: Colors.chakra.yellow,
    messages: [
      'My body is strong, resilient, and energized.',
      'I nourish myself with choices that heal me.',
      'Vitality flows through every cell in my body.',
      'I feel calm, balanced, and healthy.',
      'My body knows how to restore itself.',
      'I move with strength and ease.',
      'Rest is part of my wellness, not a reward I earn.',
      'I listen to my body’s signals with compassion.',
      'Hydration, sleep, and breath are sacred basics I honor.',
      'Healing happens in layers and I allow the process.',
      'I trade shame for care when I tend to my health.',
      'My energy returns when I pace myself wisely.',
      'I celebrate small wins that compound over time.',
      'Stress loosens its grip when I slow down and reset.',
      'I am building habits that my future self will thank me for.',
      'My health is a relationship I nurture every day.',
    ],
  },
  Peace: {
    title: 'Peace & Mental Calm',
    icon: 'flower',
    color: Colors.chakra.blue,
    messages: [
      'I breathe in calm and exhale tension.',
      'My mind is quiet, clear, and centered.',
      'Peace surrounds me and lives within me.',
      'I release worry and trust the present moment.',
      'I am grounded, safe, and steady.',
      'Stillness restores me completely.',
      'I let go of what I cannot control.',
      'Softness is strength when I stop forcing outcomes.',
      'My nervous system settles when I feel my feet on the earth.',
      'I return to my breath whenever the world feels loud.',
      'I forgive the past and free myself to be present.',
      'Peace is a practice I choose again and again.',
      'I do not need to solve everything today.',
      'Gentle thoughts create room for clarity.',
      'I am allowed to rest without justification.',
      'Serenity deepens when I stop arguing with reality.',
    ],
  },
  Focus: {
    title: 'Focus & Achievement',
    icon: 'locate',
    color: Colors.chakra.indigo,
    messages: [
      'I focus easily and finish what I start.',
      'My goals are clear and I move toward them daily.',
      'I turn distractions into determination.',
      'I am disciplined, driven, and consistent.',
      'I make progress with every small step.',
      'Success builds through my focused effort.',
      'I do the next right thing, then the next.',
      'Deep work flows when I protect my attention.',
      'I break big goals into actions I can start today.',
      'Momentum grows when I show up even on ordinary days.',
      'I learn fast because I review, adjust, and repeat.',
      'Procrastination fades when I name the first tiny step.',
      'I celebrate completion, not just starting.',
      'My environment supports the focus I want to keep.',
      'I say no to good options so I can say yes to great ones.',
      'Excellence is a series of focused reps, not a single sprint.',
    ],
  },
};
